[package]
name = "echtvar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "echtvar_lib"
path = "src/lib/mod.rs"

[[bin]]
name = "echtvar"
path = "src/main.rs"

[dependencies]
rust-htslib = { version = "*", features = ["libdeflate"] }
bitpacking = "0.8.4"
c2rust-bitfields = "0.3.0"
libc = "*"
# TODO: try deflate-miniz, deflate-zlib
zip = { version = "0.5", default-features = false, features=["deflate-miniz"] }
byteorder = "1"
# TODO: serde_msgpack or bincode
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = "fat"
codegen-units = 1
target = "x86_64"



